/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    tenants: Tenant;
    users: User;
    'api-keys': ApiKey;
    'herocare-brand-assets': HerocareBrandAsset;
    'herocare-email-templates': HerocareEmailTemplate;
    'herocare-image-gallery': HerocareImageGallery;
    'herocare-forms': HerocareForm;
    'herocare-submissions': HerocareSubmission;
    'herocare-website': HerocareWebsite;
    'emergency-hero-brand-assets': EmergencyHeroBrandAsset;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'herocare-forms': {
      submissions: 'herocare-submissions';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'herocare-brand-assets': HerocareBrandAssetsSelect<false> | HerocareBrandAssetsSelect<true>;
    'herocare-email-templates': HerocareEmailTemplatesSelect<false> | HerocareEmailTemplatesSelect<true>;
    'herocare-image-gallery': HerocareImageGallerySelect<false> | HerocareImageGallerySelect<true>;
    'herocare-forms': HerocareFormsSelect<false> | HerocareFormsSelect<true>;
    'herocare-submissions': HerocareSubmissionsSelect<false> | HerocareSubmissionsSelect<true>;
    'herocare-website': HerocareWebsiteSelect<false> | HerocareWebsiteSelect<true>;
    'emergency-hero-brand-assets': EmergencyHeroBrandAssetsSelect<false> | EmergencyHeroBrandAssetsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL-safe identifier e.g. herocare
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super-admin' | 'admin';
  /**
   * Assigned tenants — applies to Admin role only
   */
  tenants?: (number | Tenant)[] | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  tenant: number | Tenant;
  cloudflareDeployHook?: string | null;
  resendFromName?: string | null;
  resendFromEmail?: string | null;
  crmWebhookURL?: string | null;
  crmAPIKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-brand-assets".
 */
export interface HerocareBrandAsset {
  id: number;
  name: string;
  description?: string | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-email-templates".
 */
export interface HerocareEmailTemplate {
  id: number;
  tenant: number | Tenant;
  name: 'admin-notification' | 'customer-notification';
  subjectLine: string;
  logo?: (number | null) | HerocareBrandAsset;
  heading: string;
  bodyText: string;
  buttonText?: string | null;
  buttonURL?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-image-gallery".
 */
export interface HerocareImageGallery {
  id: number;
  alt: string;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-forms".
 */
export interface HerocareForm {
  id: number;
  tenant: number | Tenant;
  /**
   * e.g. Homeowner Popup, Header Form
   */
  name: string;
  /**
   * e.g. Homepage, Pricing
   */
  page: string;
  /**
   * Number of times the form was seen
   */
  views?: number | null;
  /**
   * Number of times a user started interacting
   */
  attempts?: number | null;
  /**
   * Number of successful submissions
   */
  completions?: number | null;
  /**
   * Submissions for this form
   */
  submissions?: {
    docs?: (number | HerocareSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-submissions".
 */
export interface HerocareSubmission {
  id: number;
  tenant: number | Tenant;
  /**
   * The form this submission belongs to
   */
  form: number | HerocareForm;
  journey: 'homeowner' | 'landlord';
  trigger: 'button-click' | 'header-form';
  stage: 'step-1' | 'step-2';
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  name?: string | null;
  postcode?: string | null;
  companyName?: string | null;
  numberOfProperties?: number | null;
  phoneNumber?: string | null;
  submittedAt?: string | null;
  webhookStatus?: ('pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-website".
 */
export interface HerocareWebsite {
  id: number;
  tenant: number | Tenant;
  title?: string | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  phoneNumber?: string | null;
  navCtaText?: string | null;
  navCtaLink?: string | null;
  topBarHomeownersLabel?: string | null;
  topBarHomeownersURL?: string | null;
  topBarLandlordsLabel?: string | null;
  topBarLandlordsURL?: string | null;
  emergencyHeroLogo?: (number | null) | Media;
  emergencyHeroLink?: string | null;
  trustpilotRating?: number | null;
  trustpilotReviewCount?: number | null;
  trustpilotLink?: string | null;
  heroHeadlineLine1?: string | null;
  heroHeadlineLine2?: string | null;
  heroBulletPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  heroFormSubheading?: string | null;
  heroFormCtaText?: string | null;
  heroImage?: (number | null) | Media;
  includedHeadlineLine1?: string | null;
  includedHeadlineLine2?: string | null;
  includedSubheading?: string | null;
  includedCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  howItWorksHeadline?: string | null;
  howItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  whyUsHeadlineLine1?: string | null;
  whyUsHeadlineLine2?: string | null;
  whyUsSubheading?: string | null;
  whyUsCtaText?: string | null;
  whyUsCtaLink?: string | null;
  whyUsCards?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  faqsHeadlineLine1?: string | null;
  faqsHeadlineLine2?: string | null;
  faqsSubheading?: string | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  ctaHeadlineLine1?: string | null;
  ctaHeadlineLine2?: string | null;
  ctaSubheading?: string | null;
  ctaButtonText?: string | null;
  ctaButtonLink?: string | null;
  ctaImage?: (number | null) | Media;
  popupHeadline?: string | null;
  popupSubheading?: string | null;
  popupImage?: (number | null) | Media;
  popupCtaText?: string | null;
  popupThankYouMessage?: string | null;
  thankYouHeadlineLine1?: string | null;
  thankYouHeadlineLine2?: string | null;
  thankYouPlanHeadlineLine1?: string | null;
  thankYouPlanHeadlineLine2?: string | null;
  thankYouPlanCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  thankYouSeeEverythingText?: string | null;
  landlordHeroHeadlineLine1?: string | null;
  landlordHeroHeadlineLine2?: string | null;
  landlordHeroBulletPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  landlordHeroCtaText?: string | null;
  landlordHeroImage?: (number | null) | Media;
  landlordIncludedHeadlineLine1?: string | null;
  landlordIncludedHeadlineLine2?: string | null;
  landlordIncludedSubheading?: string | null;
  landlordIncludedCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  landlordHowItWorksHeadline?: string | null;
  landlordHowItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  landlordWhyUsHeadlineLine1?: string | null;
  landlordWhyUsHeadlineLine2?: string | null;
  landlordWhyUsSubheading?: string | null;
  landlordWhyUsCtaText?: string | null;
  landlordWhyUsCtaLink?: string | null;
  landlordWhyUsCards?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  landlordFaqsHeadlineLine1?: string | null;
  landlordFaqsHeadlineLine2?: string | null;
  landlordFaqsSubheading?: string | null;
  landlordFaqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  landlordCtaHeadlineLine1?: string | null;
  landlordCtaHeadlineLine2?: string | null;
  landlordCtaSubheading?: string | null;
  landlordCtaButtonText?: string | null;
  landlordCtaButtonLink?: string | null;
  landlordCtaImage?: (number | null) | Media;
  landlordPopupHeadline?: string | null;
  landlordPopupSubheading?: string | null;
  landlordPopupImage?: (number | null) | Media;
  landlordPopupCtaText?: string | null;
  landlordPopupThankYouMessage?: string | null;
  pricingHeroHeadlineLine1?: string | null;
  pricingHeroHeadlineLine2?: string | null;
  pricingHeroSubheading?: string | null;
  calloutFeeLabel?: string | null;
  calloutFeeDescription?: string | null;
  calloutFeeOptions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  plans?:
    | {
        name: string;
        priceHighCallout?: string | null;
        priceLowCallout?: string | null;
        pricePeriod?: string | null;
        ctaText?: string | null;
        stripeLink?: string | null;
        highlightColour?: string | null;
        id?: string | null;
      }[]
    | null;
  featureRows?:
    | {
        icon?: (number | null) | Media;
        featureName: string;
        includedInPlan1?: boolean | null;
        includedInPlan2?: boolean | null;
        includedInPlan3?: boolean | null;
        id?: string | null;
      }[]
    | null;
  aboutYourPlanAccordion?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutYourPlanCtaHeadlineLine1?: string | null;
  aboutYourPlanCtaHeadlineLine2?: string | null;
  aboutYourPlanCtaPhone?: string | null;
  policies?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-brand-assets".
 */
export interface EmergencyHeroBrandAsset {
  id: number;
  name: string;
  description?: string | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'herocare-brand-assets';
        value: number | HerocareBrandAsset;
      } | null)
    | ({
        relationTo: 'herocare-email-templates';
        value: number | HerocareEmailTemplate;
      } | null)
    | ({
        relationTo: 'herocare-image-gallery';
        value: number | HerocareImageGallery;
      } | null)
    | ({
        relationTo: 'herocare-forms';
        value: number | HerocareForm;
      } | null)
    | ({
        relationTo: 'herocare-submissions';
        value: number | HerocareSubmission;
      } | null)
    | ({
        relationTo: 'herocare-website';
        value: number | HerocareWebsite;
      } | null)
    | ({
        relationTo: 'emergency-hero-brand-assets';
        value: number | EmergencyHeroBrandAsset;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenants?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  tenant?: T;
  cloudflareDeployHook?: T;
  resendFromName?: T;
  resendFromEmail?: T;
  crmWebhookURL?: T;
  crmAPIKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-brand-assets_select".
 */
export interface HerocareBrandAssetsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-email-templates_select".
 */
export interface HerocareEmailTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  subjectLine?: T;
  logo?: T;
  heading?: T;
  bodyText?: T;
  buttonText?: T;
  buttonURL?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-image-gallery_select".
 */
export interface HerocareImageGallerySelect<T extends boolean = true> {
  alt?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-forms_select".
 */
export interface HerocareFormsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  page?: T;
  views?: T;
  attempts?: T;
  completions?: T;
  submissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-submissions_select".
 */
export interface HerocareSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  form?: T;
  journey?: T;
  trigger?: T;
  stage?: T;
  device?: T;
  name?: T;
  postcode?: T;
  companyName?: T;
  numberOfProperties?: T;
  phoneNumber?: T;
  submittedAt?: T;
  webhookStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-website_select".
 */
export interface HerocareWebsiteSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  phoneNumber?: T;
  navCtaText?: T;
  navCtaLink?: T;
  topBarHomeownersLabel?: T;
  topBarHomeownersURL?: T;
  topBarLandlordsLabel?: T;
  topBarLandlordsURL?: T;
  emergencyHeroLogo?: T;
  emergencyHeroLink?: T;
  trustpilotRating?: T;
  trustpilotReviewCount?: T;
  trustpilotLink?: T;
  heroHeadlineLine1?: T;
  heroHeadlineLine2?: T;
  heroBulletPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroFormSubheading?: T;
  heroFormCtaText?: T;
  heroImage?: T;
  includedHeadlineLine1?: T;
  includedHeadlineLine2?: T;
  includedSubheading?: T;
  includedCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  howItWorksHeadline?: T;
  howItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  whyUsHeadlineLine1?: T;
  whyUsHeadlineLine2?: T;
  whyUsSubheading?: T;
  whyUsCtaText?: T;
  whyUsCtaLink?: T;
  whyUsCards?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  faqsHeadlineLine1?: T;
  faqsHeadlineLine2?: T;
  faqsSubheading?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  ctaHeadlineLine1?: T;
  ctaHeadlineLine2?: T;
  ctaSubheading?: T;
  ctaButtonText?: T;
  ctaButtonLink?: T;
  ctaImage?: T;
  popupHeadline?: T;
  popupSubheading?: T;
  popupImage?: T;
  popupCtaText?: T;
  popupThankYouMessage?: T;
  thankYouHeadlineLine1?: T;
  thankYouHeadlineLine2?: T;
  thankYouPlanHeadlineLine1?: T;
  thankYouPlanHeadlineLine2?: T;
  thankYouPlanCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  thankYouSeeEverythingText?: T;
  landlordHeroHeadlineLine1?: T;
  landlordHeroHeadlineLine2?: T;
  landlordHeroBulletPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  landlordHeroCtaText?: T;
  landlordHeroImage?: T;
  landlordIncludedHeadlineLine1?: T;
  landlordIncludedHeadlineLine2?: T;
  landlordIncludedSubheading?: T;
  landlordIncludedCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  landlordHowItWorksHeadline?: T;
  landlordHowItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  landlordWhyUsHeadlineLine1?: T;
  landlordWhyUsHeadlineLine2?: T;
  landlordWhyUsSubheading?: T;
  landlordWhyUsCtaText?: T;
  landlordWhyUsCtaLink?: T;
  landlordWhyUsCards?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  landlordFaqsHeadlineLine1?: T;
  landlordFaqsHeadlineLine2?: T;
  landlordFaqsSubheading?: T;
  landlordFaqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  landlordCtaHeadlineLine1?: T;
  landlordCtaHeadlineLine2?: T;
  landlordCtaSubheading?: T;
  landlordCtaButtonText?: T;
  landlordCtaButtonLink?: T;
  landlordCtaImage?: T;
  landlordPopupHeadline?: T;
  landlordPopupSubheading?: T;
  landlordPopupImage?: T;
  landlordPopupCtaText?: T;
  landlordPopupThankYouMessage?: T;
  pricingHeroHeadlineLine1?: T;
  pricingHeroHeadlineLine2?: T;
  pricingHeroSubheading?: T;
  calloutFeeLabel?: T;
  calloutFeeDescription?: T;
  calloutFeeOptions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  plans?:
    | T
    | {
        name?: T;
        priceHighCallout?: T;
        priceLowCallout?: T;
        pricePeriod?: T;
        ctaText?: T;
        stripeLink?: T;
        highlightColour?: T;
        id?: T;
      };
  featureRows?:
    | T
    | {
        icon?: T;
        featureName?: T;
        includedInPlan1?: T;
        includedInPlan2?: T;
        includedInPlan3?: T;
        id?: T;
      };
  aboutYourPlanAccordion?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  aboutYourPlanCtaHeadlineLine1?: T;
  aboutYourPlanCtaHeadlineLine2?: T;
  aboutYourPlanCtaPhone?: T;
  policies?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-brand-assets_select".
 */
export interface EmergencyHeroBrandAssetsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}