/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    tenants: Tenant;
    users: User;
    'api-keys': ApiKey;
    'herocare-brand-assets': HerocareBrandAsset;
    'herocare-email-templates': HerocareEmailTemplate;
    'herocare-image-gallery': HerocareImageGallery;
    'herocare-forms': HerocareForm;
    'herocare-submissions': HerocareSubmission;
    'herocare-website': HerocareWebsite;
    'emergency-hero-brand-assets': EmergencyHeroBrandAsset;
    'emergency-hero-website': EmergencyHeroWebsite;
    'emergency-hero-services': EmergencyHeroService;
    'emergency-hero-knowledge-base': EmergencyHeroKnowledgeBase;
    'emergency-hero-team-members': EmergencyHeroTeamMember;
    'emergency-hero-submissions': EmergencyHeroSubmission;
    'emergency-hero-image-gallery': EmergencyHeroImageGallery;
    'emergency-hero-email-templates': EmergencyHeroEmailTemplate;
    reviews: Review;
    'review-website-website': ReviewWebsiteWebsite;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'herocare-forms': {
      submissions: 'herocare-submissions';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'herocare-brand-assets': HerocareBrandAssetsSelect<false> | HerocareBrandAssetsSelect<true>;
    'herocare-email-templates': HerocareEmailTemplatesSelect<false> | HerocareEmailTemplatesSelect<true>;
    'herocare-image-gallery': HerocareImageGallerySelect<false> | HerocareImageGallerySelect<true>;
    'herocare-forms': HerocareFormsSelect<false> | HerocareFormsSelect<true>;
    'herocare-submissions': HerocareSubmissionsSelect<false> | HerocareSubmissionsSelect<true>;
    'herocare-website': HerocareWebsiteSelect<false> | HerocareWebsiteSelect<true>;
    'emergency-hero-brand-assets': EmergencyHeroBrandAssetsSelect<false> | EmergencyHeroBrandAssetsSelect<true>;
    'emergency-hero-website': EmergencyHeroWebsiteSelect<false> | EmergencyHeroWebsiteSelect<true>;
    'emergency-hero-services': EmergencyHeroServicesSelect<false> | EmergencyHeroServicesSelect<true>;
    'emergency-hero-knowledge-base': EmergencyHeroKnowledgeBaseSelect<false> | EmergencyHeroKnowledgeBaseSelect<true>;
    'emergency-hero-team-members': EmergencyHeroTeamMembersSelect<false> | EmergencyHeroTeamMembersSelect<true>;
    'emergency-hero-submissions': EmergencyHeroSubmissionsSelect<false> | EmergencyHeroSubmissionsSelect<true>;
    'emergency-hero-image-gallery': EmergencyHeroImageGallerySelect<false> | EmergencyHeroImageGallerySelect<true>;
    'emergency-hero-email-templates': EmergencyHeroEmailTemplatesSelect<false> | EmergencyHeroEmailTemplatesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'review-website-website': ReviewWebsiteWebsiteSelect<false> | ReviewWebsiteWebsiteSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL-safe identifier e.g. herocare
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super-admin' | 'admin';
  /**
   * Assigned tenants — applies to Admin role only
   */
  tenants?: (number | Tenant)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  tenant: number | Tenant;
  cloudflareDeployHook?: string | null;
  resendFromName?: string | null;
  resendFromEmail?: string | null;
  crmWebhookURL?: string | null;
  crmAPIKey?: string | null;
  /**
   * e.g. G-XXXXXXXXXX — leave blank to disable GA4
   */
  ga4MeasurementId?: string | null;
  /**
   * e.g. GTM-XXXXXXX — leave blank to disable GTM
   */
  gtmContainerId?: string | null;
  /**
   * Third-party snippets injected into the site at build time — e.g. pixels, chat widgets, ClickFunnels
   */
  scripts?:
    | {
        /**
         * e.g. Meta Pixel, ClickFunnels
         */
        name: string;
        placement: 'head' | 'body-start' | 'body-end';
        /**
         * Paste the full snippet exactly as the tool provides it, including script tags
         */
        code: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-brand-assets".
 */
export interface HerocareBrandAsset {
  id: number;
  name: string;
  description?: string | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-email-templates".
 */
export interface HerocareEmailTemplate {
  id: number;
  tenant: number | Tenant;
  name: 'admin-notification' | 'customer-notification';
  subjectLine: string;
  logo?: (number | null) | HerocareBrandAsset;
  heading: string;
  bodyText: string;
  buttonText?: string | null;
  buttonURL?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-image-gallery".
 */
export interface HerocareImageGallery {
  id: number;
  alt: string;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-forms".
 */
export interface HerocareForm {
  id: number;
  tenant: number | Tenant;
  /**
   * e.g. Homeowner Popup, Header Form
   */
  name: string;
  /**
   * e.g. Homepage, Pricing
   */
  page: string;
  /**
   * Send notification emails when this form receives a submission
   */
  notificationsEnabled?: boolean | null;
  /**
   * Email addresses that receive a notification for each submission — include the GHL ingestion address here
   */
  notificationRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Number of times the form was seen
   */
  views?: number | null;
  /**
   * Number of times a user started interacting
   */
  attempts?: number | null;
  /**
   * Number of successful submissions
   */
  completions?: number | null;
  /**
   * Submissions for this form
   */
  submissions?: {
    docs?: (number | HerocareSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-submissions".
 */
export interface HerocareSubmission {
  id: number;
  tenant: number | Tenant;
  /**
   * The form this submission belongs to
   */
  form: number | HerocareForm;
  journey: 'homeowner' | 'landlord';
  trigger: 'button-click' | 'header-form';
  stage: 'step-1' | 'step-2';
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  name?: string | null;
  postcode?: string | null;
  companyName?: string | null;
  numberOfProperties?: number | null;
  phoneNumber?: string | null;
  email?: string | null;
  submittedAt?: string | null;
  webhookStatus?: ('pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-website".
 */
export interface HerocareWebsite {
  id: number;
  tenant: number | Tenant;
  title?: string | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  phoneNumber?: string | null;
  navCtaText?: string | null;
  navCtaLink?: string | null;
  topBarHomeownersLabel?: string | null;
  topBarHomeownersURL?: string | null;
  topBarLandlordsLabel?: string | null;
  topBarLandlordsURL?: string | null;
  emergencyHeroLogo?: (number | null) | Media;
  emergencyHeroLink?: string | null;
  trustpilotRating?: number | null;
  trustpilotReviewCount?: number | null;
  trustpilotLink?: string | null;
  heroBackgroundImage?: (number | null) | Media;
  heroHeadlineLine1?: string | null;
  heroHeadlineLine2?: string | null;
  heroBulletPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  heroFormSubheading?: string | null;
  heroFormCtaText?: string | null;
  heroImage?: (number | null) | Media;
  includedHeadlineLine1?: string | null;
  includedHeadlineLine2?: string | null;
  includedSubheading?: string | null;
  includedCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        id?: string | null;
      }[]
    | null;
  howItWorksHeadline?: string | null;
  howItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  whyUsHeadlineLine1?: string | null;
  whyUsHeadlineLine2?: string | null;
  whyUsSubheading?: string | null;
  whyUsCtaText?: string | null;
  whyUsCards?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  faqsHeadlineLine1?: string | null;
  faqsHeadlineLine2?: string | null;
  faqsSubheading?: string | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  ctaHeadlineLine1?: string | null;
  ctaHeadlineLine2?: string | null;
  ctaSubheading?: string | null;
  ctaButtonText?: string | null;
  ctaImage?: (number | null) | Media;
  popupHeadline?: string | null;
  popupImage?: (number | null) | Media;
  popupCtaText?: string | null;
  popupThankYouMessage?: string | null;
  tyHeadlineLine1?: string | null;
  tyHeadlineLine2?: string | null;
  tySubheading?: string | null;
  tyAppStoreLink?: string | null;
  tyGooglePlayLink?: string | null;
  tyPlanHeadlineLine1?: string | null;
  tyPlanHeadlineLine2?: string | null;
  landlordHeroHeadlineLine1?: string | null;
  landlordHeroHeadlineLine2?: string | null;
  landlordHeroBulletPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  landlordHeroCtaText?: string | null;
  landlordHeroImage?: (number | null) | Media;
  landlordIncludedHeadlineLine1?: string | null;
  landlordIncludedHeadlineLine2?: string | null;
  landlordIncludedSubheading?: string | null;
  landlordIncludedCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        id?: string | null;
      }[]
    | null;
  landlordHowItWorksHeadline?: string | null;
  landlordHowItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  landlordWhyUsHeadlineLine1?: string | null;
  landlordWhyUsHeadlineLine2?: string | null;
  landlordWhyUsSubheading?: string | null;
  landlordWhyUsCtaText?: string | null;
  landlordWhyUsCards?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  landlordFaqsHeadlineLine1?: string | null;
  landlordFaqsHeadlineLine2?: string | null;
  landlordFaqsSubheading?: string | null;
  landlordFaqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  landlordCtaHeadlineLine1?: string | null;
  landlordCtaHeadlineLine2?: string | null;
  landlordCtaSubheading?: string | null;
  landlordCtaButtonText?: string | null;
  landlordCtaImage?: (number | null) | Media;
  landlordPopupHeadline?: string | null;
  landlordPopupImage?: (number | null) | Media;
  landlordPopupCtaText?: string | null;
  calloutFeeLabel?: string | null;
  calloutFeeDescription?: string | null;
  calloutFeeOptions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  plans?:
    | {
        name: string;
        priceHighCallout?: string | null;
        priceLowCallout?: string | null;
        pricePeriod?: string | null;
        ctaText?: string | null;
        stripeLinkHighCallout?: string | null;
        stripeLinkLowCallout?: string | null;
        highlightColour?: string | null;
        id?: string | null;
      }[]
    | null;
  featureRows?:
    | {
        icon?: (number | null) | Media;
        featureName: string;
        includedInPlan1?: boolean | null;
        includedInPlan2?: boolean | null;
        worthNoting?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutYourPlanAccordion?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutYourPlanCtaHeadlineLine1?: string | null;
  aboutYourPlanCtaHeadlineLine2?: string | null;
  aboutYourPlanCtaPhone?: string | null;
  policies?:
    | {
        title: string;
        footerLinkLabel?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-brand-assets".
 */
export interface EmergencyHeroBrandAsset {
  id: number;
  name: string;
  description?: string | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-website".
 */
export interface EmergencyHeroWebsite {
  id: number;
  tenant: number | Tenant;
  title?: string | null;
  logoLight?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  phoneNumber?: string | null;
  navCtaText?: string | null;
  trustpilotRating?: number | null;
  trustpilotReviewCount?: string | null;
  trustpilotPlatformsLabel?: string | null;
  appStoreUrl?: string | null;
  googlePlayUrl?: string | null;
  appScreenshotImage?: (number | null) | Media;
  appBlockHeadline?: string | null;
  appBlockBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  appBlockBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  bottomCtaHeadline?: string | null;
  bottomCtaButtonText?: string | null;
  bottomCtaImageLeft?: (number | null) | Media;
  bottomCtaImageRight?: (number | null) | Media;
  footerStrapline?: string | null;
  footerFacebookUrl?: string | null;
  footerInstagramUrl?: string | null;
  footerTwitterUrl?: string | null;
  footerAppBannerImage?: (number | null) | Media;
  footerCopyrightText?: string | null;
  footerServicesLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerCompanyLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerPoliciesLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  mobileMenuImageLeft?: (number | null) | Media;
  mobileMenuImageRight?: (number | null) | Media;
  homeHeroBackgroundImage?: (number | null) | Media;
  homeHeroHeadline?: string | null;
  homeHeroSubheading?: string | null;
  homeHeroFormCtaText?: string | null;
  homeHeroImageLeft?: (number | null) | Media;
  homeHeroImageRight?: (number | null) | Media;
  homeModalHeadline?: string | null;
  homeModalCharacterImage?: (number | null) | EmergencyHeroImageGallery;
  logoBarLogos?:
    | {
        image: number | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  servicesGridHeadline?: string | null;
  servicesGridSubheading?: string | null;
  homecareCardHeadline?: string | null;
  homecareCardBody?: string | null;
  homecareCardCtaText?: string | null;
  homecareCardCtaUrl?: string | null;
  homecareCardImage?: (number | null) | Media;
  homecareCardAccentColour?: string | null;
  whoWeAreHeadline?: string | null;
  whoWeAreSubheading?: string | null;
  whoWeAreVideoUrl?: string | null;
  homeFaqsHeadline?: string | null;
  homeFaqsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  homeFaqsHaveAnotherQuestion?: string | null;
  homeFaqItems?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  knowledgeBaseHeadline?: string | null;
  plumbingHeroBgImage?: (number | null) | Media;
  plumbingHeroHeadline?: string | null;
  plumbingHeroSubheading?: string | null;
  plumbingHeroFormCtaText?: string | null;
  plumbingIssuesHeadline?: string | null;
  plumbingIssuesSubheading?: string | null;
  plumbingIssueCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        id?: string | null;
      }[]
    | null;
  plumbingWhyUsHeadline?: string | null;
  plumbingWhyUsSubheading?: string | null;
  plumbingWhyUsCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  plumbingHowItWorksHeadline?: string | null;
  plumbingHowItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  plumbingFaqsHeadline?: string | null;
  plumbingFaqsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  plumbingFaqItems?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  plumbingTySubheading?: string | null;
  plumbingTyCallCtaText?: string | null;
  heatingHeroBgImage?: (number | null) | Media;
  heatingHeroHeadline?: string | null;
  heatingHeroSubheading?: string | null;
  heatingHeroFormCtaText?: string | null;
  heatingIssuesHeadline?: string | null;
  heatingIssuesSubheading?: string | null;
  heatingIssueCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        id?: string | null;
      }[]
    | null;
  heatingWhyUsHeadline?: string | null;
  heatingWhyUsSubheading?: string | null;
  heatingWhyUsCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  heatingHowItWorksHeadline?: string | null;
  heatingHowItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  heatingFaqsHeadline?: string | null;
  heatingFaqsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heatingFaqItems?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  heatingTySubheading?: string | null;
  heatingTyCallCtaText?: string | null;
  electricsHeroBgImage?: (number | null) | Media;
  electricsHeroHeadline?: string | null;
  electricsHeroSubheading?: string | null;
  electricsHeroFormCtaText?: string | null;
  electricsIssuesHeadline?: string | null;
  electricsIssuesSubheading?: string | null;
  electricsIssueCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        id?: string | null;
      }[]
    | null;
  electricsWhyUsHeadline?: string | null;
  electricsWhyUsSubheading?: string | null;
  electricsWhyUsCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  electricsHowItWorksHeadline?: string | null;
  electricsHowItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  electricsFaqsHeadline?: string | null;
  electricsFaqsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  electricsFaqItems?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  electricsTySubheading?: string | null;
  electricsTyCallCtaText?: string | null;
  drainageHeroBgImage?: (number | null) | Media;
  drainageHeroHeadline?: string | null;
  drainageHeroSubheading?: string | null;
  drainageHeroFormCtaText?: string | null;
  drainageIssuesHeadline?: string | null;
  drainageIssuesSubheading?: string | null;
  drainageIssueCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        id?: string | null;
      }[]
    | null;
  drainageWhyUsHeadline?: string | null;
  drainageWhyUsSubheading?: string | null;
  drainageWhyUsCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  drainageHowItWorksHeadline?: string | null;
  drainageHowItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  drainageFaqsHeadline?: string | null;
  drainageFaqsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  drainageFaqItems?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  drainageTySubheading?: string | null;
  drainageTyCallCtaText?: string | null;
  locksmithsHeroBgImage?: (number | null) | Media;
  locksmithsHeroHeadline?: string | null;
  locksmithsHeroSubheading?: string | null;
  locksmithsHeroFormCtaText?: string | null;
  locksmithsIssuesHeadline?: string | null;
  locksmithsIssuesSubheading?: string | null;
  locksmithsIssueCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        ctaText?: string | null;
        id?: string | null;
      }[]
    | null;
  locksmithsWhyUsHeadline?: string | null;
  locksmithsWhyUsSubheading?: string | null;
  locksmithsWhyUsCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  locksmithsHowItWorksHeadline?: string | null;
  locksmithsHowItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  locksmithsFaqsHeadline?: string | null;
  locksmithsFaqsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  locksmithsFaqItems?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  locksmithsTySubheading?: string | null;
  locksmithsTyCallCtaText?: string | null;
  kbHeroBgImage?: (number | null) | Media;
  kbHeroHeadline?: string | null;
  kbHeroSubheading?: string | null;
  kbGridHeadline?: string | null;
  aboutHeroBgImage?: (number | null) | Media;
  aboutHeroHeadline?: string | null;
  aboutHeroSubheading?: string | null;
  asSeenOnLabel?: string | null;
  asSeenOnLogos?:
    | {
        image: number | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  storyBlocks?:
    | {
        image?: (number | null) | Media;
        headline: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  brandValuesHeadline?: string | null;
  brandValuesSubheading?: string | null;
  brandValueCards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  teamHeadline?: string | null;
  teamBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bahHeroBgImage?: (number | null) | Media;
  bahHeroHeadline?: string | null;
  bahHeroSubheading?: string | null;
  bahHeroCtaText?: string | null;
  bahHowItWorksHeadline?: string | null;
  bahHowItWorksSteps?:
    | {
        image?: (number | null) | Media;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  bahPlansHeadline?: string | null;
  bahPlansSubheading?: string | null;
  bahPlans?:
    | {
        name: string;
        ctaText?: string | null;
        stripeLink?: string | null;
        id?: string | null;
      }[]
    | null;
  bahFeatureRows?:
    | {
        featureName: string;
        planValues?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bahPlansFootnote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bahStoryImage?: (number | null) | Media;
  bahStoryHeadline?: string | null;
  bahStoryBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bahStoryCtaText?: string | null;
  bahStoryCtaLink?: string | null;
  bahTradeDocuments?:
    | {
        tradeName: string;
        tradePluralLabel: string;
        microcopy?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        requiredDocuments?:
          | {
              label: string;
              required?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ehPolicies?:
    | {
        title: string;
        slug: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-image-gallery".
 */
export interface EmergencyHeroImageGallery {
  id: number;
  tenant: number | Tenant;
  altText?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-services".
 */
export interface EmergencyHeroService {
  id: number;
  tenant: number | Tenant;
  serviceName: string;
  slug: string;
  enabled?: boolean | null;
  accentColour?: string | null;
  navLabel?: string | null;
  categoryLabel?: string | null;
  heroCharacterImageDesktop?: (number | null) | Media;
  heroCharacterImageMobile?: (number | null) | Media;
  heroBackgroundImage?: (number | null) | Media;
  reviewCategory?: string | null;
  rngMin?: number | null;
  rngMax?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-knowledge-base".
 */
export interface EmergencyHeroKnowledgeBase {
  id: number;
  tenant: number | Tenant;
  title: string;
  slug: string;
  category: 'plumbing' | 'heating' | 'electrics' | 'drainage' | 'locksmiths' | 'homecare' | 'company';
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  bodyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-team-members".
 */
export interface EmergencyHeroTeamMember {
  id: number;
  tenant: number | Tenant;
  name: string;
  jobTitle?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-submissions".
 */
export interface EmergencyHeroSubmission {
  id: number;
  tenant: number | Tenant;
  name?: string | null;
  companyName?: string | null;
  companyType?: string | null;
  email?: string | null;
  mobile?: string | null;
  website?: string | null;
  skills?:
    | {
        trade?: string | null;
        id?: string | null;
      }[]
    | null;
  uploadedDocuments?:
    | {
        tradeName?: string | null;
        documentLabel?: string | null;
        fileUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  workingDaysHours?: string | null;
  postcode?: string | null;
  coverageRadius?: number | null;
  comments?: string | null;
  submittedAt?: string | null;
  ghlWebhookStatus?: ('pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-email-templates".
 */
export interface EmergencyHeroEmailTemplate {
  id: number;
  tenant: number | Tenant;
  templateName: 'admin-notification' | 'customer-notification';
  subjectLine?: string | null;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttonText?: string | null;
  buttonUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  customerName: string;
  rating: '1' | '2' | '3' | '4' | '5';
  serviceType: 'plumbing' | 'heating' | 'electrics' | 'drainage' | 'general';
  reviewBody?: string | null;
  date?: string | null;
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-website-website".
 */
export interface ReviewWebsiteWebsite {
  id: number;
  internalTitle?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  navLinkVisitWebsiteLabel?: string | null;
  navLinkVisitWebsiteUrl?: string | null;
  navLinkGetHomeCoverLabel?: string | null;
  navLinkGetHomeCoverUrl?: string | null;
  navCtaLabel?: string | null;
  heroHeadline?: string | null;
  heroSubheading?: string | null;
  heroImage?: (number | null) | Media;
  heroRatingText?: string | null;
  heroReviewCount?: string | null;
  platformLogos?:
    | {
        logo?: (number | null) | Media;
        url?: string | null;
        altText?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewsSectionHeadline?: string | null;
  filterLabel?: string | null;
  filterImages?:
    | {
        serviceType: 'general' | 'heating' | 'plumbing' | 'drainage' | 'electrics';
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  popupHeadline?: string | null;
  popupImage?: (number | null) | Media;
  popupCtaLabel?: string | null;
  popupThankYouMessage?: string | null;
  footerLogo?: (number | null) | Media;
  footerPrivacyPolicyUrl?: string | null;
  footerCookiesPolicyUrl?: string | null;
  footerVisitMainWebsiteUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'herocare-brand-assets';
        value: number | HerocareBrandAsset;
      } | null)
    | ({
        relationTo: 'herocare-email-templates';
        value: number | HerocareEmailTemplate;
      } | null)
    | ({
        relationTo: 'herocare-image-gallery';
        value: number | HerocareImageGallery;
      } | null)
    | ({
        relationTo: 'herocare-forms';
        value: number | HerocareForm;
      } | null)
    | ({
        relationTo: 'herocare-submissions';
        value: number | HerocareSubmission;
      } | null)
    | ({
        relationTo: 'herocare-website';
        value: number | HerocareWebsite;
      } | null)
    | ({
        relationTo: 'emergency-hero-brand-assets';
        value: number | EmergencyHeroBrandAsset;
      } | null)
    | ({
        relationTo: 'emergency-hero-website';
        value: number | EmergencyHeroWebsite;
      } | null)
    | ({
        relationTo: 'emergency-hero-services';
        value: number | EmergencyHeroService;
      } | null)
    | ({
        relationTo: 'emergency-hero-knowledge-base';
        value: number | EmergencyHeroKnowledgeBase;
      } | null)
    | ({
        relationTo: 'emergency-hero-team-members';
        value: number | EmergencyHeroTeamMember;
      } | null)
    | ({
        relationTo: 'emergency-hero-submissions';
        value: number | EmergencyHeroSubmission;
      } | null)
    | ({
        relationTo: 'emergency-hero-image-gallery';
        value: number | EmergencyHeroImageGallery;
      } | null)
    | ({
        relationTo: 'emergency-hero-email-templates';
        value: number | EmergencyHeroEmailTemplate;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'review-website-website';
        value: number | ReviewWebsiteWebsite;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenants?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  tenant?: T;
  cloudflareDeployHook?: T;
  resendFromName?: T;
  resendFromEmail?: T;
  crmWebhookURL?: T;
  crmAPIKey?: T;
  ga4MeasurementId?: T;
  gtmContainerId?: T;
  scripts?:
    | T
    | {
        name?: T;
        placement?: T;
        code?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-brand-assets_select".
 */
export interface HerocareBrandAssetsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-email-templates_select".
 */
export interface HerocareEmailTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  subjectLine?: T;
  logo?: T;
  heading?: T;
  bodyText?: T;
  buttonText?: T;
  buttonURL?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-image-gallery_select".
 */
export interface HerocareImageGallerySelect<T extends boolean = true> {
  alt?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-forms_select".
 */
export interface HerocareFormsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  page?: T;
  notificationsEnabled?: T;
  notificationRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  views?: T;
  attempts?: T;
  completions?: T;
  submissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-submissions_select".
 */
export interface HerocareSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  form?: T;
  journey?: T;
  trigger?: T;
  stage?: T;
  device?: T;
  name?: T;
  postcode?: T;
  companyName?: T;
  numberOfProperties?: T;
  phoneNumber?: T;
  email?: T;
  submittedAt?: T;
  webhookStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herocare-website_select".
 */
export interface HerocareWebsiteSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  phoneNumber?: T;
  navCtaText?: T;
  navCtaLink?: T;
  topBarHomeownersLabel?: T;
  topBarHomeownersURL?: T;
  topBarLandlordsLabel?: T;
  topBarLandlordsURL?: T;
  emergencyHeroLogo?: T;
  emergencyHeroLink?: T;
  trustpilotRating?: T;
  trustpilotReviewCount?: T;
  trustpilotLink?: T;
  heroBackgroundImage?: T;
  heroHeadlineLine1?: T;
  heroHeadlineLine2?: T;
  heroBulletPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroFormSubheading?: T;
  heroFormCtaText?: T;
  heroImage?: T;
  includedHeadlineLine1?: T;
  includedHeadlineLine2?: T;
  includedSubheading?: T;
  includedCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        id?: T;
      };
  howItWorksHeadline?: T;
  howItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  whyUsHeadlineLine1?: T;
  whyUsHeadlineLine2?: T;
  whyUsSubheading?: T;
  whyUsCtaText?: T;
  whyUsCards?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  faqsHeadlineLine1?: T;
  faqsHeadlineLine2?: T;
  faqsSubheading?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  ctaHeadlineLine1?: T;
  ctaHeadlineLine2?: T;
  ctaSubheading?: T;
  ctaButtonText?: T;
  ctaImage?: T;
  popupHeadline?: T;
  popupImage?: T;
  popupCtaText?: T;
  popupThankYouMessage?: T;
  tyHeadlineLine1?: T;
  tyHeadlineLine2?: T;
  tySubheading?: T;
  tyAppStoreLink?: T;
  tyGooglePlayLink?: T;
  tyPlanHeadlineLine1?: T;
  tyPlanHeadlineLine2?: T;
  landlordHeroHeadlineLine1?: T;
  landlordHeroHeadlineLine2?: T;
  landlordHeroBulletPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  landlordHeroCtaText?: T;
  landlordHeroImage?: T;
  landlordIncludedHeadlineLine1?: T;
  landlordIncludedHeadlineLine2?: T;
  landlordIncludedSubheading?: T;
  landlordIncludedCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        id?: T;
      };
  landlordHowItWorksHeadline?: T;
  landlordHowItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  landlordWhyUsHeadlineLine1?: T;
  landlordWhyUsHeadlineLine2?: T;
  landlordWhyUsSubheading?: T;
  landlordWhyUsCtaText?: T;
  landlordWhyUsCards?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  landlordFaqsHeadlineLine1?: T;
  landlordFaqsHeadlineLine2?: T;
  landlordFaqsSubheading?: T;
  landlordFaqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  landlordCtaHeadlineLine1?: T;
  landlordCtaHeadlineLine2?: T;
  landlordCtaSubheading?: T;
  landlordCtaButtonText?: T;
  landlordCtaImage?: T;
  landlordPopupHeadline?: T;
  landlordPopupImage?: T;
  landlordPopupCtaText?: T;
  calloutFeeLabel?: T;
  calloutFeeDescription?: T;
  calloutFeeOptions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  plans?:
    | T
    | {
        name?: T;
        priceHighCallout?: T;
        priceLowCallout?: T;
        pricePeriod?: T;
        ctaText?: T;
        stripeLinkHighCallout?: T;
        stripeLinkLowCallout?: T;
        highlightColour?: T;
        id?: T;
      };
  featureRows?:
    | T
    | {
        icon?: T;
        featureName?: T;
        includedInPlan1?: T;
        includedInPlan2?: T;
        worthNoting?: T;
        id?: T;
      };
  aboutYourPlanAccordion?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  aboutYourPlanCtaHeadlineLine1?: T;
  aboutYourPlanCtaHeadlineLine2?: T;
  aboutYourPlanCtaPhone?: T;
  policies?:
    | T
    | {
        title?: T;
        footerLinkLabel?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-brand-assets_select".
 */
export interface EmergencyHeroBrandAssetsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-website_select".
 */
export interface EmergencyHeroWebsiteSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  logoLight?: T;
  logoDark?: T;
  favicon?: T;
  phoneNumber?: T;
  navCtaText?: T;
  trustpilotRating?: T;
  trustpilotReviewCount?: T;
  trustpilotPlatformsLabel?: T;
  appStoreUrl?: T;
  googlePlayUrl?: T;
  appScreenshotImage?: T;
  appBlockHeadline?: T;
  appBlockBody?: T;
  appBlockBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bottomCtaHeadline?: T;
  bottomCtaButtonText?: T;
  bottomCtaImageLeft?: T;
  bottomCtaImageRight?: T;
  footerStrapline?: T;
  footerFacebookUrl?: T;
  footerInstagramUrl?: T;
  footerTwitterUrl?: T;
  footerAppBannerImage?: T;
  footerCopyrightText?: T;
  footerServicesLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerCompanyLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerPoliciesLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  mobileMenuImageLeft?: T;
  mobileMenuImageRight?: T;
  homeHeroBackgroundImage?: T;
  homeHeroHeadline?: T;
  homeHeroSubheading?: T;
  homeHeroFormCtaText?: T;
  homeHeroImageLeft?: T;
  homeHeroImageRight?: T;
  homeModalHeadline?: T;
  homeModalCharacterImage?: T;
  logoBarLogos?:
    | T
    | {
        image?: T;
        url?: T;
        id?: T;
      };
  servicesGridHeadline?: T;
  servicesGridSubheading?: T;
  homecareCardHeadline?: T;
  homecareCardBody?: T;
  homecareCardCtaText?: T;
  homecareCardCtaUrl?: T;
  homecareCardImage?: T;
  homecareCardAccentColour?: T;
  whoWeAreHeadline?: T;
  whoWeAreSubheading?: T;
  whoWeAreVideoUrl?: T;
  homeFaqsHeadline?: T;
  homeFaqsBody?: T;
  homeFaqsHaveAnotherQuestion?: T;
  homeFaqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  knowledgeBaseHeadline?: T;
  plumbingHeroBgImage?: T;
  plumbingHeroHeadline?: T;
  plumbingHeroSubheading?: T;
  plumbingHeroFormCtaText?: T;
  plumbingIssuesHeadline?: T;
  plumbingIssuesSubheading?: T;
  plumbingIssueCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        id?: T;
      };
  plumbingWhyUsHeadline?: T;
  plumbingWhyUsSubheading?: T;
  plumbingWhyUsCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  plumbingHowItWorksHeadline?: T;
  plumbingHowItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  plumbingFaqsHeadline?: T;
  plumbingFaqsBody?: T;
  plumbingFaqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  plumbingTySubheading?: T;
  plumbingTyCallCtaText?: T;
  heatingHeroBgImage?: T;
  heatingHeroHeadline?: T;
  heatingHeroSubheading?: T;
  heatingHeroFormCtaText?: T;
  heatingIssuesHeadline?: T;
  heatingIssuesSubheading?: T;
  heatingIssueCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        id?: T;
      };
  heatingWhyUsHeadline?: T;
  heatingWhyUsSubheading?: T;
  heatingWhyUsCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  heatingHowItWorksHeadline?: T;
  heatingHowItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  heatingFaqsHeadline?: T;
  heatingFaqsBody?: T;
  heatingFaqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  heatingTySubheading?: T;
  heatingTyCallCtaText?: T;
  electricsHeroBgImage?: T;
  electricsHeroHeadline?: T;
  electricsHeroSubheading?: T;
  electricsHeroFormCtaText?: T;
  electricsIssuesHeadline?: T;
  electricsIssuesSubheading?: T;
  electricsIssueCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        id?: T;
      };
  electricsWhyUsHeadline?: T;
  electricsWhyUsSubheading?: T;
  electricsWhyUsCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  electricsHowItWorksHeadline?: T;
  electricsHowItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  electricsFaqsHeadline?: T;
  electricsFaqsBody?: T;
  electricsFaqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  electricsTySubheading?: T;
  electricsTyCallCtaText?: T;
  drainageHeroBgImage?: T;
  drainageHeroHeadline?: T;
  drainageHeroSubheading?: T;
  drainageHeroFormCtaText?: T;
  drainageIssuesHeadline?: T;
  drainageIssuesSubheading?: T;
  drainageIssueCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        id?: T;
      };
  drainageWhyUsHeadline?: T;
  drainageWhyUsSubheading?: T;
  drainageWhyUsCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  drainageHowItWorksHeadline?: T;
  drainageHowItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  drainageFaqsHeadline?: T;
  drainageFaqsBody?: T;
  drainageFaqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  drainageTySubheading?: T;
  drainageTyCallCtaText?: T;
  locksmithsHeroBgImage?: T;
  locksmithsHeroHeadline?: T;
  locksmithsHeroSubheading?: T;
  locksmithsHeroFormCtaText?: T;
  locksmithsIssuesHeadline?: T;
  locksmithsIssuesSubheading?: T;
  locksmithsIssueCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        ctaText?: T;
        id?: T;
      };
  locksmithsWhyUsHeadline?: T;
  locksmithsWhyUsSubheading?: T;
  locksmithsWhyUsCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  locksmithsHowItWorksHeadline?: T;
  locksmithsHowItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  locksmithsFaqsHeadline?: T;
  locksmithsFaqsBody?: T;
  locksmithsFaqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  locksmithsTySubheading?: T;
  locksmithsTyCallCtaText?: T;
  kbHeroBgImage?: T;
  kbHeroHeadline?: T;
  kbHeroSubheading?: T;
  kbGridHeadline?: T;
  aboutHeroBgImage?: T;
  aboutHeroHeadline?: T;
  aboutHeroSubheading?: T;
  asSeenOnLabel?: T;
  asSeenOnLogos?:
    | T
    | {
        image?: T;
        url?: T;
        id?: T;
      };
  storyBlocks?:
    | T
    | {
        image?: T;
        headline?: T;
        body?: T;
        id?: T;
      };
  brandValuesHeadline?: T;
  brandValuesSubheading?: T;
  brandValueCards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  teamHeadline?: T;
  teamBody?: T;
  bahHeroBgImage?: T;
  bahHeroHeadline?: T;
  bahHeroSubheading?: T;
  bahHeroCtaText?: T;
  bahHowItWorksHeadline?: T;
  bahHowItWorksSteps?:
    | T
    | {
        image?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  bahPlansHeadline?: T;
  bahPlansSubheading?: T;
  bahPlans?:
    | T
    | {
        name?: T;
        ctaText?: T;
        stripeLink?: T;
        id?: T;
      };
  bahFeatureRows?:
    | T
    | {
        featureName?: T;
        planValues?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  bahPlansFootnote?: T;
  bahStoryImage?: T;
  bahStoryHeadline?: T;
  bahStoryBody?: T;
  bahStoryCtaText?: T;
  bahStoryCtaLink?: T;
  bahTradeDocuments?:
    | T
    | {
        tradeName?: T;
        tradePluralLabel?: T;
        microcopy?: T;
        requiredDocuments?:
          | T
          | {
              label?: T;
              required?: T;
              id?: T;
            };
        id?: T;
      };
  ehPolicies?:
    | T
    | {
        title?: T;
        slug?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-services_select".
 */
export interface EmergencyHeroServicesSelect<T extends boolean = true> {
  tenant?: T;
  serviceName?: T;
  slug?: T;
  enabled?: T;
  accentColour?: T;
  navLabel?: T;
  categoryLabel?: T;
  heroCharacterImageDesktop?: T;
  heroCharacterImageMobile?: T;
  heroBackgroundImage?: T;
  reviewCategory?: T;
  rngMin?: T;
  rngMax?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-knowledge-base_select".
 */
export interface EmergencyHeroKnowledgeBaseSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  heroImage?: T;
  bodyContent?: T;
  featured?: T;
  publishedAt?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-team-members_select".
 */
export interface EmergencyHeroTeamMembersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  jobTitle?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-submissions_select".
 */
export interface EmergencyHeroSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  companyName?: T;
  companyType?: T;
  email?: T;
  mobile?: T;
  website?: T;
  skills?:
    | T
    | {
        trade?: T;
        id?: T;
      };
  uploadedDocuments?:
    | T
    | {
        tradeName?: T;
        documentLabel?: T;
        fileUrl?: T;
        id?: T;
      };
  workingDaysHours?: T;
  postcode?: T;
  coverageRadius?: T;
  comments?: T;
  submittedAt?: T;
  ghlWebhookStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-image-gallery_select".
 */
export interface EmergencyHeroImageGallerySelect<T extends boolean = true> {
  tenant?: T;
  altText?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-hero-email-templates_select".
 */
export interface EmergencyHeroEmailTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  templateName?: T;
  subjectLine?: T;
  heading?: T;
  body?: T;
  buttonText?: T;
  buttonUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  customerName?: T;
  rating?: T;
  serviceType?: T;
  reviewBody?: T;
  date?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-website-website_select".
 */
export interface ReviewWebsiteWebsiteSelect<T extends boolean = true> {
  internalTitle?: T;
  logo?: T;
  favicon?: T;
  navLinkVisitWebsiteLabel?: T;
  navLinkVisitWebsiteUrl?: T;
  navLinkGetHomeCoverLabel?: T;
  navLinkGetHomeCoverUrl?: T;
  navCtaLabel?: T;
  heroHeadline?: T;
  heroSubheading?: T;
  heroImage?: T;
  heroRatingText?: T;
  heroReviewCount?: T;
  platformLogos?:
    | T
    | {
        logo?: T;
        url?: T;
        altText?: T;
        id?: T;
      };
  reviewsSectionHeadline?: T;
  filterLabel?: T;
  filterImages?:
    | T
    | {
        serviceType?: T;
        image?: T;
        id?: T;
      };
  popupHeadline?: T;
  popupImage?: T;
  popupCtaLabel?: T;
  popupThankYouMessage?: T;
  footerLogo?: T;
  footerPrivacyPolicyUrl?: T;
  footerCookiesPolicyUrl?: T;
  footerVisitMainWebsiteUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}